"""change file_path to object_path

Revision ID: 0a2ba0fc9c8a
Revises: 5027637138fe
Create Date: 2025-10-04 18:24:00.403303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a2ba0fc9c8a'
down_revision: Union[str, Sequence[str], None] = '5027637138fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('object_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('document', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('document', 'object_path')
    # ### end Alembic commands ###
