"""alter embedding table

Revision ID: 22d8c7fe9116
Revises: 4f589f1d4eca
Create Date: 2025-10-05 18:27:34.845509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22d8c7fe9116'
down_revision: Union[str, Sequence[str], None] = '4f589f1d4eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('chunk_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_embedding_chunks_id'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_user_id'), table_name='embedding')
    op.create_index(op.f('ix_embedding_chunk_id'), 'embedding', ['chunk_id'], unique=False)
    op.drop_constraint(op.f('embedding_chunks_id_fkey'), 'embedding', type_='foreignkey')
    op.create_foreign_key(None, 'embedding', 'chunk', ['chunk_id'], ['id'])
    op.drop_column('embedding', 'chunks_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('chunks_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.create_foreign_key(op.f('embedding_chunks_id_fkey'), 'embedding', 'chunk', ['chunks_id'], ['id'])
    op.drop_index(op.f('ix_embedding_chunk_id'), table_name='embedding')
    op.create_index(op.f('ix_embedding_user_id'), 'embedding', ['user_id'], unique=False)
    op.create_index(op.f('ix_embedding_chunks_id'), 'embedding', ['chunks_id'], unique=False)
    op.drop_column('embedding', 'chunk_id')
    # ### end Alembic commands ###
