"""ondelete on

Revision ID: 288b9ae0bbc9
Revises: 045da7d9cc2f
Create Date: 2025-10-07 13:34:33.901561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '288b9ae0bbc9'
down_revision: Union[str, Sequence[str], None] = '045da7d9cc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunk_document_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'document', ['document_id'], ['id'])
    op.drop_constraint(op.f('embedding_chunk_id_fkey'), 'embedding', type_='foreignkey')
    op.create_foreign_key(None, 'embedding', 'chunk', ['chunk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.create_foreign_key(op.f('embedding_chunk_id_fkey'), 'embedding', 'chunk', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_document_id_fkey'), 'chunk', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
