"""ondelete on

Revision ID: 3ad1fcd7e12b
Revises: 48267dffa6fe
Create Date: 2025-10-07 13:06:25.378577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ad1fcd7e12b'
down_revision: Union[str, Sequence[str], None] = '48267dffa6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embedding_chunk_id_fkey'), 'embedding', type_='foreignkey')
    op.create_foreign_key(None, 'embedding', 'chunk', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.create_foreign_key(op.f('embedding_chunk_id_fkey'), 'embedding', 'chunk', ['chunk_id'], ['id'])
    # ### end Alembic commands ###
