"""alter embedding to vector

Revision ID: 4f589f1d4eca
Revises: e84c6f88a784
Create Date: 2025-10-05 17:54:13.656364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f589f1d4eca'
down_revision: Union[str, Sequence[str], None] = 'e84c6f88a784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.drop_index(op.f('sqlmodel_index'), table_name='embedding', postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('sqlmodel_index', 'embedding', ['vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'vector': 'vector_l2_ops'})
    op.drop_column('embedding', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_index('sqlmodel_index', table_name='embedding', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_index(op.f('sqlmodel_index'), 'embedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('embedding', 'vector')
    # ### end Alembic commands ###
