"""file_file in document table is deleted

Revision ID: dcf720de80f8
Revises: 0a2ba0fc9c8a
Create Date: 2025-10-04 21:37:15.293169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcf720de80f8'
down_revision: Union[str, Sequence[str], None] = '0a2ba0fc9c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
