"""add user_id fk in embedding table

Revision ID: e84c6f88a784
Revises: 5366a090aebe
Create Date: 2025-10-05 17:50:19.974944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e84c6f88a784'
down_revision: Union[str, Sequence[str], None] = '5366a090aebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_embedding_user_id'), 'embedding', ['user_id'], unique=False)
    op.create_foreign_key(None, 'embedding', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.drop_index(op.f('ix_embedding_user_id'), table_name='embedding')
    op.drop_column('embedding', 'user_id')
    # ### end Alembic commands ###
