"""init vector_db

Revision ID: f53d5cdc12a7
Revises: 
Create Date: 2025-09-15 13:22:10.194107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f53d5cdc12a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sqlmodel_index', 'item', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sqlmodel_index', table_name='item', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('item')
    # ### end Alembic commands ###
